from fastapi import APIRouter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import os

router = APIRouter()

OUTPUT_DIR = "outputs/reports"

@router.post("/")
def generate_report(data: dict, filename: str = "cam_report.pdf"):

    file_path = os.path.join(OUTPUT_DIR, filename)

    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()

    content = []

    # 🔹 Title
    content.append(Paragraph("Credit Appraisal Memo (CAM)", styles["Title"]))
    content.append(Spacer(1, 20))

    # 🔹 Risk
    content.append(Paragraph(f"<b>Risk Level:</b> {data.get('risk')}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # 🔹 Features
    content.append(Paragraph("<b>Financial Features:</b>", styles["Heading2"]))
    features = data.get("features", {})
    for key, value in features.items():
        content.append(Paragraph(f"{key}: {value}", styles["Normal"]))

    content.append(Spacer(1, 15))

    # 🔹 Decision
    content.append(Paragraph("<b>Decision:</b>", styles["Heading2"]))
    decision = data.get("decision", "")
    content.append(Paragraph(str(decision), styles["Normal"]))

    content.append(Spacer(1, 15))

    # 🔹 Reasons
    content.append(Paragraph("<b>Reasons:</b>", styles["Heading2"]))
    for reason in data.get("reasons", []):
        content.append(Paragraph(f"- {reason}", styles["Normal"]))

    content.append(Spacer(1, 20))

    # 🔹 Footer
    content.append(Paragraph("Generated by Intelli-Credit AI System", styles["Italic"]))

    doc.build(content)

    return {
        "report_path": file_path
    }